//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.Presentation.AgentDoctorFeatures {
    
    
    public partial class AgentDoctorSendPackage {
        
        /// <summary>
        /// AgentDoctorSendPackageAlertWindowDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl AgentDoctorSendPackageAlertWindowDiv;
        
        /// <summary>
        /// AgentDoctorSendPackageAlertWindowContentLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AgentDoctorSendPackageAlertWindowContentLabel;
        
        /// <summary>
        /// AgentDoctorSendPackageDestination control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AgentDoctorSendPackageDestination;
        
        /// <summary>
        /// AgentDoctorSendingDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList AgentDoctorSendingDropDownList;
        
        /// <summary>
        /// AgentDoctorSendPackageTypebarcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox AgentDoctorSendPackageTypebarcode;
        
        /// <summary>
        /// AgentDoctorSendPackageTypeButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AgentDoctorSendPackageTypeButton;
    }
}
