//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.Presentation.AgentDoctorFeatures {
    
    
    public partial class AgentDoctorRegisterPackage {
        
        /// <summary>
        /// AgentDoctorPackageRegisterPackageTypeDropDwonList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList AgentDoctorPackageRegisterPackageTypeDropDwonList;
        
        /// <summary>
        /// NedPackageRegisterFormExpireDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox NedPackageRegisterFormExpireDate;
        
        /// <summary>
        /// RFVagentdoctorSendPackageFieldValid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RFVagentdoctorSendPackageFieldValid;
        
        /// <summary>
        /// REVagentdoctorSendPackageExpressValid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator REVagentdoctorSendPackageExpressValid;
        
        /// <summary>
        /// AgentDoctorRegisterMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AgentDoctorRegisterMessage;
        
        /// <summary>
        /// AgentDoctorRegisterBarcodeImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image AgentDoctorRegisterBarcodeImage;
        
        /// <summary>
        /// AgentDoctorRegisterButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button AgentDoctorRegisterButton;
    }
}
