//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ENETCare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a different distribution centre.
        /// </summary>
        internal static string AnotherDistributionCentre {
            get {
                return ResourceManager.GetString("AnotherDistributionCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution centre not found.
        /// </summary>
        internal static string DistributionCentreNotFound {
            get {
                return ResourceManager.GetString("DistributionCentreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package destination distribution centre is not correct.
        /// </summary>
        internal static string IncorrectDistributionCentreDestination {
            get {
                return ResourceManager.GetString("IncorrectDistributionCentreDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package source distribution centre is not correct.
        /// </summary>
        internal static string IncorrectDistributionCentreSource {
            get {
                return ResourceManager.GetString("IncorrectDistributionCentreSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package stock distribution centre is not correct.
        /// </summary>
        internal static string IncorrectDistributionCentreStock {
            get {
                return ResourceManager.GetString("IncorrectDistributionCentreStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package status is not correct.
        /// </summary>
        internal static string IncorrectPackageStatus {
            get {
                return ResourceManager.GetString("IncorrectPackageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format.
        /// </summary>
        internal static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication package not found.
        /// </summary>
        internal static string MedicationPackageNotFound {
            get {
                return ResourceManager.GetString("MedicationPackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication type not found.
        /// </summary>
        internal static string MedicationTypeNotFound {
            get {
                return ResourceManager.GetString("MedicationTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medication type not matched.
        /// </summary>
        internal static string MedicationTypeNotMatched {
            get {
                return ResourceManager.GetString("MedicationTypeNotMatched", resourceCulture);
            }
        }
    }
}
