//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENETCare.Presentation.DoctorFeatures {
    
    
    public partial class DoctorRegisterPackage {
        
        /// <summary>
        /// DoctorRegisterPackageTypeDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DoctorRegisterPackageTypeDropDownList;
        
        /// <summary>
        /// DoctorRegisterPackageFormExpireDateTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox DoctorRegisterPackageFormExpireDateTextBox;
        
        /// <summary>
        /// DoctorRegisterMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label DoctorRegisterMessage;
        
        /// <summary>
        /// DoctorRegisterBarcodeImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image DoctorRegisterBarcodeImage;
        
        /// <summary>
        /// DoctorRegisterButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button DoctorRegisterButton;
    }
}
